services:
  postgres:
    container_name: postgres-sql-ac
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: agriconnect
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - agriconnect-network
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-ac
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"

networks:
  agriconnect-network:
    driver: bridge

volumes:
  postgres:
    driver: local