spring:
  application:
    name: agriconnect
    security:
      jwt:
        secret-key: 5fadbfed784644f631bb0bdb7a36c9e30435e21cd51ca77c35b00adafd296970
        expiration: 8640000

  datasource:
    url: jdbc:postgresql://localhost:5432/agriconnect
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025
    username: sdq
    password: sdq
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000


