spring:
  application:
    name: agriconnect
  datasource:
    url: jdbc:postgresql://localhost:5432/agriconnect
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
